name: Deploy Jupyter Book

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "jupyter-book"
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -U jupyter-book ghp-import

      - name: Build book
        run: jb build .

      - name: Deploy to gh-pages
        run: ghp-import -n -p -f _build/html
